name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y libdevel-nytprof-perl
      - run: python -m pip install -e .[dev] pytest
      - run: pytest -q
      - name: profile & render
        run: |
          python -m pynytprof.tracer tests/example_script.py
          nytprofhtml -f nytprof.out -o report
          test -f report/index.html

